praticandoOBI/obi/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from provasobi.views import home
from django.conf import settings
from django.conf.urls.static import static
from usuarios.views import activate
from django.conf import settings

urlpatterns = [
                  path('', home, name='home'),
                  path('admin/', admin.site.urls),
                  path('provas/', include('provasobi.urls', namespace='provas_obi')),
                  path('usuario/', include('usuarios.urls', namespace='usuarios_obi')),
                  url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
                      activate, name='activate'),
                  url(r'^nested_admin/', include('nested_admin.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

praticandoOBI/provasobi/urls.py
from django.urls import path
from provasobi.views import home, materiais, provas, problemas, busca, buscaprob, problema

app_name = 'provas_obi'
urlpatterns = [
    path('', provas, name='url_provas'),
    path('<int:pk>/problemas/', problemas, name='url_prob'),
    path('busca/', busca, name='url_busca'),
    path('buscaproblemas/', buscaprob, name='url_buscaprob'),
    path('problema/<int:pk>/', problema, name='url_prob_info'),
    path('materiais/', materiais, name='url_materiais'),
]

praticandoOBI/usuarios/urls.py
from django.urls import path
from django.conf.urls import include
from usuarios.views import upload_drive, gabarito, busca, provaperson_baixar, busca, provaperson_excluir, provaperson_baixar_docx, dadosbanco, update_perfil, cadastro_perfil, questoes_add, questoes_busca, home_usuario, provaperson, provaperson_detail, provaperson_edit, provasperson, provaperson_pronta
from django.contrib.auth import views as auth_views

app_name = 'usuarios_obi'
urlpatterns = [
    path('', home_usuario, name='homeusuario'),
    path('cadastro/', cadastro_perfil, name='cadastro_perfil'),

    path('banco/', dadosbanco, name='dadosbanco'),
    path('login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login_perfil'),
    path('login/', include('registration.backends.default.urls')),
    path('logout/', auth_views.LogoutView.as_view(template_name='home.html'), name='logout_perfil'),
    path('minhasprovas/', provasperson, name='provasperson'),
    path('novaprova/', provaperson, name='provaperson'),
    path('minhaprova/editar/<int:pk>/', provaperson_edit, name='provaperson_edit'),
    path('minhaprova/editar/<int:pk>/buscaquestoes/', questoes_busca, name='questoes_busca'),

    path('minhaprova/busca/', busca, name='url_busca'),
    path('minhaprova/editar/<int:pk>/busca/', busca, name='busca'),

    #path('minhaprova/<int:pk>/', provaperson_detail, name='provaperson_detail'),
    # path('minhasprovas/pdf/', Pdf.as_view(), name='provaperson_baixar'),

    path('minhaprova/editar/<int:codproblema>/adquestoes/<int:pk>/', questoes_add, name='questoes_add'),
    path('minhaprova/<int:codprova>/', provaperson_pronta, name='provaperson_pronta'),
    path('minhaprova/excluir/<int:pk>/', provaperson_excluir, name='provaperson_excluir'),

    path('minhaprova/<int:codprova>/gabarito', gabarito, name='url_gabarito'),

    path('minhaprova/<int:codprova>/baixarprova/', provaperson_baixar, name='provaperson_baixar'),
    path('minhaprova/<int:codprova>/baixarprova_docx/', provaperson_baixar_docx, name='provaperson_baixar_docx'),
    path('minhaprova/<int:codprova>/upload_drive/', upload_drive, name='upload_drive'),
]

praticandoOBI/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Pratique OBI</title>

    <!--<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">-->
    <!--<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">-->
    <!--<link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>-->
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">

    <link href="{% static 'images/obicon.ico' %}" rel="shortcut icon">
    <!--<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">-->

    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css">
</head>
<style>
    a:hover {
        color: #f2ba00;
    }
</style>
<body style="background-color: ">


<div id="wrapper" class="animate">
    <nav class="navbar header-top fixed-top navbar-expand-lg  navbar-light" style="background-color: #54a9ff;">
        <a class="navbar-brand" href="{% url 'home' %}"> Pratique OBI</a>

        <button class="navbar-toggler" type="button" data-target="#navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav animate side-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'home' %}">Home
                        <span class="sr-only">(current)</span>
                    </a>
                </li>
                <li>
                    <a class="nav-link" href="{% url 'provas_obi:url_provas' %}">Provas Passadas</a>
                    <span class="sr-only">(current)</span>
                </li>
                <li>
                    <a class="nav-link" href="{% url 'provas_obi:url_busca' %}">Busca</a>
                    <span class="sr-only">(current)</span>
                </li>

                <!--<li class="nav-item dropdown">-->
                <!--<a class="nav-link dropdown-toggle" href="#" id="navdrop" role="button" data-toggle="dropdown"-->
                <!--data-hover="dropdown">Buscar</a>-->
                <!--<div class="dropdown-menu" aria-labelledby="navdrop">-->
                <!--<a href="{% url 'provas_obi:url_busca' %}" class="dropdown-item">Prova</a>-->
                <!--<a href="{% url 'provas_obi:url_buscaprob' %}" class="dropdown-item">Problema</a>-->
                <!--</div>-->
                <!--</li>-->
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'usuarios_obi:provaperson' %}">Nova Prova</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'usuarios_obi:provasperson' %}">Minhas Provas</a>
                    </li>
                {% endif %}
            </ul>
            <ul class="navbar-nav ml-md-auto d-md-flex">
                <li>
                    <a class="nav-link" href="{% url 'provas_obi:url_materiais' %}">Mais<b>+</b></a>
                    <span class="sr-only">(current)</span>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'usuarios_obi:logout_perfil' %}">Sair</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'usuarios_obi:login_perfil' %}">Acesso
                            <span class="sr-only">(current)</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'usuarios_obi:cadastro_perfil' %}">Criar Conta
                            <span class="sr-only">(current)</span>
                        </a>
                    </li>
                {% endif %}
            </ul>
        </div>

    </nav>

    <div class="copy-banner" style="margin-top: 85px;">
        <p style="margin-left: 10px; padding: 10px; color: white; font-size:28px; ">
            {% block titulo %}

            {% endblock %}</p>
    </div>

    {% block messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissable"
                 style="width: 10%; float:right; text-align: center;">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <strong>{{ message }}</strong>
            </div>
        {% endfor %}
    {% endblock messages %}
    <div style="margin-bottom:50px;" class="container">
        {% block container %}
        {% endblock %}
    </div>


    <div class="container-fluid">
        <div class="row">

            {% block content %}
            {% endblock %}

        </div>
    </div>
</div>
</body>


{% block scripts %}
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
            integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
            crossorigin="anonymous"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"
            integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4"
            crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"
            integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1"
            crossorigin="anonymous"></script>

    <script type="text/javascript" charset="utf8"
            src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js"></script>

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-143000977-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];

        function gtag() {
            dataLayer.push(arguments);
        }

        gtag('js', new Date());

        gtag('config', 'UA-143000977-1');
    </script>


    {% block extra_scripts %}
    {% endblock %}
{% endblock %}

</html>

praticandoOBI/templates/base2.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Pratique OBI</title>
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
            integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"
            integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4"
            crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"
            integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1"
            crossorigin="anonymous"></script>
    <link href="{% static 'images/obicon.ico' %}" rel="shortcut icon">

</head>
<style>
    a:hover {
        color: #f2ba00;
    }

</style>
<body>

<div id="wrapper" class="animate">
    <nav class="navbar header-top fixed-top navbar-expand-lg  navbar-light" style="background-color: #54a9ff;">
        <a class="navbar-brand" href="{% url 'home' %}"> Pratique OBI</a>
        <button class="navbar-toggler" type="button" data-target="#navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav animate side-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'home' %}">Home
                        <span class="sr-only">(current)</span>
                    </a>
                </li>
                <li>
                    <a class="nav-link" href="{% url 'provas_obi:url_provas' %}">Provas Passadas</a>
                    <span class="sr-only">(current)</span>
                </li>
                <li>
                    <a class="nav-link" href="{% url 'provas_obi:url_busca' %}">Busca</a>
                    <span class="sr-only">(current)</span>
                </li>
                <!--<li class="nav-item dropdown">-->
                <!--<a class="nav-link dropdown-toggle" href="#" id="navdrop" role="button" data-toggle="dropdown" data-hover="dropdown">Buscar</a>-->
                <!--<div class="dropdown-menu" aria-labelledby="navdrop">-->
                <!--<a href="{% url 'provas_obi:url_busca' %}" class="dropdown-item">Prova</a>-->
                <!--<a href="{% url 'provas_obi:url_buscaprob' %}" class="dropdown-item">Problema</a>-->
                <!--</div>-->
                <!--</li>-->
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'usuarios_obi:provaperson' %}">Nova Prova</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'usuarios_obi:provasperson' %}">Minhas Provas</a>
                    </li>
                {% endif %}

            </ul>
            <ul class="navbar-nav ml-md-auto d-md-flex">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'usuarios_obi:logout_perfil' %}">Sair</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'usuarios_obi:login_perfil' %}">Acesso
                            <span class="sr-only">(current)</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'usuarios_obi:cadastro_perfil' %}">Criar Conta
                            <span class="sr-only">(current)</span>
                        </a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <div class="copy-banner" style="margin-top: 85px;">
        <p style="margin-left: 10px; padding: 10px; color: white; font-size:28px; ">
            {% block titulo %}
                {% if user.is_authenticated %}
                    Olá, {{ user.get_username }}!
                {% else %}
                    Home
                {% endif %}
            {% endblock %}</p>
    </div>

    {% block messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissable"
                 style="width: 10%; float:right; text-align: center;">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <strong>{{ message }}</strong>
            </div>
        {% endfor %}
    {% endblock messages %}
    <div style="margin-left: 10px; margin-bottom:50px;" class="container">
        {% block container %}
        {% endblock %}
    </div>

</div>
</body>

<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-143000977-1"></script>
<script>
    window.dataLayer = window.dataLayer || [];

    function gtag() {
        dataLayer.push(arguments);
    }

    gtag('js', new Date());

    gtag('config', 'UA-143000977-1');
</script>

</html>

praticandoOBI/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}
    {% if user.is_authenticated %}
        Olá, {{ user.get_username }}!
    {% else %}
        Home
    {% endif %}
{% endblock %}

{% block container %}

<link href="{% static 'css/style2.css' %}" rel="stylesheet">
<link href="{% static 'css/footer.css' %}" rel="stylesheet">

<img src="./../static/images/Pratiqueobi-logo.png" alt="OBI" style="width:80%;" class="centro">

     <div class="container">
         <div class="centro">
            <div class="col=5 mt-9">
                <div class="jumbotron" style="background-color:transparent" style="width:100%;">
                  <p class="lead" style="font-size:25px">No Pratique OBI você pode criar provas personalizadas de maneira fácil e rápida para aplicar em treinamentos e simulados. <br>Além disso, você também pode buscar provas e problemas de OBI's passadas na Modalidade Iniciação.</p>
                    &nbsp;
                    <p style="text-align: center" class="lead">
                        {% if user.is_authenticated %}
                            <a class="btn standard-btn" href="{% url 'usuarios_obi:provaperson' %}" role="button"><b>Criar Prova</b></a>
                        {% else %}
                            <a class="btn standard-btn" href="{% url 'usuarios_obi:login_perfil' %}" role="button"><b>Criar Prova</b></a>
                        {% endif %}
                        &nbsp;
                        &nbsp;
                         <a class="btn standard-btn" href="{% url 'provas_obi:url_busca' %}" role="button"><b>Buscar Prova</b></a>
                    </p>
            </div>
         </div>
        </div>
     </div>

<img src="./../static/images/obi-logo.png" alt="OBI" style="width:10%;" class="centro">

</br><hr class="my-2"></br></br>

      <div class="container">
       <div class="row">
          <div class="col-sm-6">
            <div class="card">
              <div class="card-body">
                  <h5 class="card-title"><b>O que é a OBI?</b></h5>
                <p class="card-text">A <a href="https://olimpiada.ic.unicamp.br/">Olimpíada Brasileira de Informática</a> é uma competição de programação anual voltada a alunos de ensino básico e superior, sendo aplicadas avaliações para diferentes modalidades e níveis.<br>
                    Tem por um dos objetivos despertar nos alunos o interesse por Ciência da Computação.
                    </p>
              </div>
            </div>
          </div>

          <div class="col-sm-6">
            <div class="card">
              <div class="card-body">
                  <h5 class="card-title"><b>Como criar minhas provas?</b></h5>
                <p class="card-text">Selecione questões no nosso banco de provas passadas da OBI na Modalidade Iniciação.<br>
                    Cada prova contém vários <b>problemas</b> (título grande e centralizado) com sua descrição e regras, e com <b>questões</b> (enumeradas) relacionadas a eles.<br>
                    <br/>Crie sua própria prova, selecione as questões desejadas, salve e aplique!</p>
              </div>
            </div>
          </div>
        </div>
     </div>

{% endblock %}

{% block content %}

	<section id="footer">
		<div class="container-fluid">
			<div class="row text-center text-xs-center text-sm-left text-md-left">
				<div class="col-xs-12 col-sm-4 col-md-4">
					<h5>Menu</h5>
					<ul class="list-unstyled quick-links">
						<li><a href="{% url 'home' %}"><i class="fa fa-angle-double-right"></i>Home</a></li>
						<li><a href="{% url 'provas_obi:url_provas' %}"><i class="fa fa-angle-double-right"></i>Provas Passadas</a></li>
						<li><a href="{% url 'provas_obi:url_busca' %}"><i class="fa fa-angle-double-right"></i>Busca</a></li>
					</ul>
				</div>
				<div class="col-xs-12 col-sm-4 col-md-4">
					<h5>Links</h5>
					<ul class="list-unstyled quick-links">
						<li><a href="https://olimpiada.ic.unicamp.br/"><i class="fa fa-angle-double-right"></i>Olimpíada Brasileira de Informática</a></li>
						<li><a href="https://www.facebook.com/CompClubUFSM/"><i class="fa fa-angle-double-right"></i>Clube de Computação - UFSM</a></li>
						<li><a href="http://obi.inf.ufsm.br/"><i class="fa fa-angle-double-right"></i>OBI na UFSM</a></li>
					</ul>
				</div>
                <div class="col-xs-12 col-sm-4 col-md-4">
					<ul class="list-unstyled list-inline social text-center">
                        <h5>Fale conosco</h5><br/>
						<li class="list-inline-item"><a href="https://www.facebook.com/CompClubUFSM/"><i class="fa fa-facebook"></i></a></li>
						<li class="list-inline-item"><a href="javascript:void();" target="_blank"><i class="fa fa-envelope"></i></a></li>
					</ul>
				</div>
			</div>
		</div>
	</section>

{% endblock %}

praticandoOBI/templates/materiais.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}
    Outros materiais
{% endblock %}

{% block container %}

    <ul class="list-group">

        <li class="list-group-item" ><b> Materiais para estudo </b><br/>
        <a target="_blank" href=""> Livro </a><br/>
        <a href="">Site</a><br/>
        <a href="">Slides</a>
        </li>

        <li class="list-group-item" ><b> Outros </b><br/>
        <a href=""> Progress Code </a><br/>
        <a href=""> Logic in a logic way</a><br/>
        <a href=""> Classificação das questões</a><br/>
        <a href=""> TCC otávio </a>
        </li>

        <li class="list-group-item" ><b>Artigos sobre OBI</b><br/>
            <a href=""> Artigo </a><br/>
        </li>

        <li class="list-group-item" > <b>Fale conosco:</b><br/>
            <a href="https://www.facebook.com/CompClubUFSM/"> Clube de Computação da UFSM </a><br/>
        </li>

    </ul>

{% endblock %}

praticandoOBI/templates/minhasprovas.html
{% extends 'base2.html' %}
{% load static %}

{% block titulo %}
    Minhas Provas
{% endblock %}

{% block container %}

    {% if not provas %}
        <p>Você ainda não tem provas cadastradas.</p>
    {% else %}
    <ul class="list-group product-category-all">

    <div class="container">
    <div class="row">

        {% for prova in provas %}
      <div class="col-sm-6 mt-3">
        <div class="card">
          <div class="card-body">
              <h5 class="card-title"><b>{{ prova.titulo }}</b></h5>
            <p class="card-text">
                {% if prova.ano == None %}
                    Ano: não inserido</br>
                {% else %}
                    Ano: {{prova.ano}}</br>
                {% endif %}

                {% if prova.dificuldade == None %}
                    Dificuldade: não inserida</br>
                {% elif prova.dificuldade == 0 %}
                    Dificuldade: não inserida</br>
                {% else %}
                    Dificuldade: {{prova.dificuldade}}</br>
                {% endif %}
                Observações: {{prova.observacoes}}</br></br>
                <a href="{% url 'usuarios_obi:provaperson_edit' prova.pk %}" class="btn btn-primary" role="button" >Editar</a>
                <a href="{% url 'usuarios_obi:provaperson_pronta' prova.pk %}" class="btn btn-primary" role="button" >Visualizar</a>
                <a href="{% url 'usuarios_obi:url_gabarito' prova.pk %}" class="btn btn-primary" role="button" >Gabarito</a>
                <a href="{% url 'usuarios_obi:provaperson_excluir' prova.pk %}" class="btn btn-primary" role="button" >Excluir</a>
            </p>
          </div>
        </div>
      </div>
          {% endfor%}

      </div>
    </div>


    {% endif %}
    </ul>
{% endblock %}

praticandoOBI/templates/problemas.html
{% extends 'base2.html' %}
{% load static %}

{% block titulo %}
{% for p in provas %}
    Prova:  {{p.anoprova}} - Fase {{p.faseprova}} - Nível {{p.nivelprova}}
{% endfor %}
{% endblock %}

{% block container %}

    <button onclick="goBack()">Voltar</button>
    <script>
    function goBack() {
        window.history.back();
    }
    </script>

    {% for prob in problemas %}
    <br/>
    <h3><p align="center"><b>{{prob.tituloproblema}}</b></p></h3><br/>

        <!--Mostra a classificação do problema, se ele tiver-->
        <br><font color="#8bc34a"><b>CLASSIFICAÇÃO:</b></font>
        {% for f in prob.classificacao.all %}
            <br><b>{{f.tituloclassificacao}}</b>
        {% endfor %}

        <br/><br/>{{prob.enunciadoproblema}}</br>

        <!--Mostra as regras do problema, se ele tiver-->
        {% if prob.regrasproblema %}
            <br/>{{prob.regrasproblema}}<br/>
        {% endif %}

        <!--Mostra as imagens do problema, se ele tiver-->
        {% if prob.imgproblema %}
            {% load static %}
            <img src={% static prob.imgproblema %} width="350" alt="My image">
        {% endif %}

        <!--Mostra as questões do problema-->
        {% for q in questoes %}
            {% if q.codproblema.codproblema == prob.codproblema %}
                <br>{{ q.numeroquestao }} - {{q.enunciadoquestao}}</br>

                <!--Mostra as imagens da questão-->
                {% if q.imgquestao %}
                    {% load static %}
                    <img src={% static q.imgquestao %} width="200" height="200" alt="Img"></br>
                {% endif %}

                {#ana#}
                <!--Mostra as alternativas da questão-->
                {% for a in q.get_alternativas %}
                        {{a.letraalternativa}} - {{ a.textoalternativa }} </br>
                {% endfor %}

            <br>
             <button class="btn btn-outline-success" onclick="myFunction('{{q.codquestao}}')">Ver gabarito</button><br/>
             <div id="{{q.codquestao}}"> &nbsp;
               <div class="highlight">
                   <p><font size="6"><b><pre>{{q.gabaritoquestao}}</pre></b></font></fontziseb></p>
               </div>
             </div>

            <script>
            document.getElementById( '{{q.codquestao}}' ).style.display = 'none';
            function myFunction(elementID) {
                var x = document.getElementById(elementID);
                if (x.style.display === 'none') {
                    x.style.display = 'block';
                } else {
                    x.style.display = 'none';
                }
            }</script>

            {% endif %}
        {% endfor %}
    <hr>
    {% endfor%}
</ul>
{% endblock %}

praticandoOBI/templates/provas.html
{% extends 'base2.html' %}
{% load static %}

{% block titulo %}
    Provas
{% endblock %}

{% block container %}

    <ul class="list-group">
    {% for prova in provas %}

    <li class="list-group-item" ><b>{{ prova.anoprova }} - Fase {{prova.faseprova}} - Nível {{prova.nivelprova}}</b><br/>
    <a target="_blank" href="{{prova.urlprova}}"> Acesse </a><br/>
        <a href="{% url 'provas_obi:url_prob' prova.codprova %}">Ver problemas</a></li>
    {% endfor%}
    </ul>

{% endblock %}