praticandoOBI/obi/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from provasobi.views import home
from django.conf import settings
from django.conf.urls.static import static
from usuarios.views import activate
from django.conf import settings

urlpatterns = [
                  path('', home, name='home'),
                  path('admin/', admin.site.urls),
                  path('provas/', include('provasobi.urls', namespace='provas_obi')),
                  path('usuario/', include('usuarios.urls', namespace='usuarios_obi')),
                  url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
                      activate, name='activate'),
                  url(r'^nested_admin/', include('nested_admin.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

praticandoOBI/provasobi/urls.py
from django.urls import path
from provasobi.views import home, materiais, provas, problemas, busca, buscaprob, problema

app_name = 'provas_obi'
urlpatterns = [
    path('', provas, name='url_provas'),
    path('<int:pk>/problemas/', problemas, name='url_prob'),
    path('busca/', busca, name='url_busca'),
    path('buscaproblemas/', buscaprob, name='url_buscaprob'),
    path('problema/<int:pk>/', problema, name='url_prob_info'),
    path('materiais/', materiais, name='url_materiais'),
]

praticandoOBI/usuarios/urls.py
from django.urls import path
from django.conf.urls import include
from usuarios.views import upload_drive, gabarito, busca, provaperson_baixar, busca, provaperson_excluir, provaperson_baixar_docx, dadosbanco, update_perfil, cadastro_perfil, questoes_add, questoes_busca, home_usuario, provaperson, provaperson_detail, provaperson_edit, provasperson, provaperson_pronta
from django.contrib.auth import views as auth_views

app_name = 'usuarios_obi'
urlpatterns = [
    path('', home_usuario, name='homeusuario'),
    path('cadastro/', cadastro_perfil, name='cadastro_perfil'),

    path('banco/', dadosbanco, name='dadosbanco'),
    path('login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login_perfil'),
    path('login/', include('registration.backends.default.urls')),
    path('logout/', auth_views.LogoutView.as_view(template_name='home.html'), name='logout_perfil'),
    path('minhasprovas/', provasperson, name='provasperson'),
    path('novaprova/', provaperson, name='provaperson'),
    path('minhaprova/editar/<int:pk>/', provaperson_edit, name='provaperson_edit'),
    path('minhaprova/editar/<int:pk>/buscaquestoes/', questoes_busca, name='questoes_busca'),

    path('minhaprova/busca/', busca, name='url_busca'),
    path('minhaprova/editar/<int:pk>/busca/', busca, name='busca'),

    #path('minhaprova/<int:pk>/', provaperson_detail, name='provaperson_detail'),
    # path('minhasprovas/pdf/', Pdf.as_view(), name='provaperson_baixar'),

    path('minhaprova/editar/<int:codproblema>/adquestoes/<int:pk>/', questoes_add, name='questoes_add'),
    path('minhaprova/<int:codprova>/', provaperson_pronta, name='provaperson_pronta'),
    path('minhaprova/excluir/<int:pk>/', provaperson_excluir, name='provaperson_excluir'),

    path('minhaprova/<int:codprova>/gabarito', gabarito, name='url_gabarito'),

    path('minhaprova/<int:codprova>/baixarprova/', provaperson_baixar, name='provaperson_baixar'),
    path('minhaprova/<int:codprova>/baixarprova_docx/', provaperson_baixar_docx, name='provaperson_baixar_docx'),
    path('minhaprova/<int:codprova>/upload_drive/', upload_drive, name='upload_drive'),
]

praticandoOBI/templates/busca/busca_form.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}
    Busca
{% endblock %}

{% block container %}
    <h1>Provas</h1>

    <table id="tableprovas" class="display">
        <thead>
        <tr>
            <th>Ano / Nível / Fase</th>
            <th>Prova</th>
            <th>Gabarito</th>
        </tr>
        </thead>
        <tbody>
        {% for prova in provas %}
            <tr>
                <td> Ano {{ prova.anoprova }} / Nível {{ prova.nivelprova }} / Fase {{ prova.faseprova }}</td>
                <td><a href="{{ prova.urlprova }}">Link Prova</a></td>
                {% if prova.urlgabarito %}
                    <td><a href="{{ prova.urlgabarito }}">Link Gabarito</a></td>
                {% else %}
                    <td>Sem link cadastrado.</td>
                {% endif %}
            </tr>
        {% endfor %}
        </tbody>
    </table>


</br><hr class="my-2"></br></br>

    <h1>Problemas</h1>
    <!--<p>Buscar por título, enunciado, classificacão</p>-->

    <form action="" method="GET">
        <div class="form-group">
            {% if error %}
                <p style="color: red;">Por favor, entre com um valor.</p>
            {% endif %}

            {% if erroinput %}
                <p style="color: red;">Busca inválida, busque por um ano, nível ou fase de prova.</p>
            {% endif %}

            <div class="row">
                <div class="col-10">
                    <input type="text" class="form-control" name="q"/><br/>
                </div>
                <div class="col-2">
                    <button type="submit" class="btn btn-primary btn-block">Buscar</button>
                </div>
            </div>
        </div>
    </form>
    <table id="tableproblemas" class="display">
        <thead>
        <tr>
            <th>Ano / Nível / Fase</th>
            <th>Classificação</th>
            <th>Título</th>
        </tr>
        </thead>
        <tbody>
        {% for problema in problemas %}
            <tr>
                <td>Ano {{ problema.codprova.anoprova }} / Nível {{ problema.codprova.nivelprova }} /
                    Fase {{ problema.codprova.faseprova }}</td>
                <td>{% for class in problema.classificacao.all %}{{ class.tituloclassificacao }} {% endfor %}</td>
                <td><a href="{% url 'provas_obi:url_prob_info' problema.codproblema %}">{{ problema.tituloproblema }}</a></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}

{% block extra_scripts %}
    <script>
        $(document).ready(function () {
            $('#tableprovas').DataTable();
        });
        $(document).ready(function () {
            $('#tableproblemas').DataTable({"searching": false});
        });
    </script>
{% endblock %}

praticandoOBI/templates/busca/busca_prob_form.html
{% extends 'base.html' %}
{% load static %}

{% block caminho %}
    Provas / Busca Problemas
{% endblock %}

{% block container %}
     <form action="" method="GET">
        <div class="form-group">

            {% if error %}
                <p style="color: red;">Por favor, entre com um valor.</p>
            {% endif %}

            <div class="col-xs-9">
                <input type="text" class="form-control" name="q"/><br/>
                <label class="radio-inline">Procurar problema por: </label>&emsp;
                <label for="box1"><input type="radio" name="display_type" value="titulobox" id="box1">Título</label>&emsp;
                <label for="box2"><input type="radio" name="display_type" value="classificacaobox" id="box2">Classificação</label>&nbsp;&nbsp;
                <label for="box3"><input type="radio" name="display_type" value="palavrabox" id="box3">Palavra-chave</label>&nbsp;&nbsp;
                <label for="box4"><input type="radio" name="display_type" value="todosbox" id="box4" checked="checked">Todos</label>

            </div>
            <div class="col-xs-2">
                <button type="submit" class="btn btn-primary">Buscar</button>
            </div>
        </div>
    </form>
{% endblock %}

praticandoOBI/templates/busca/busca_prob_resultado.html
{% extends './busca_prob_form.html' %}
{% load static %}

{% block caminho %}
    {{ block.super }}
    / Resultado
{% endblock %}

{% block container %}
    <p>Resultados para: <strong>{{ query }}</strong></p>
    {% if problemas %}
        <p>Encontrou {{problemas|length }} problema{{problemas|pluralize}}. </p>
        <ul>
            {% for p in problemas %}
                <li><a href="{% url 'provas_obi:url_prob_info' p.codproblema %}">{{p.tituloproblema}} - Classificação:
                    {% for c in p.classificacao.all %}
                        {{c.tituloclassificacao}}
                    {% endfor %}
                    <!--<input type='checkbox' {% ifequal value 0 %}checked{% endifequal %}>-->
                    </a></li>
            {% endfor %}
        </ul>
    {% else %}
        <p>Nenhum resultado encontrado para a sua pesquisa.</p>
    {% endif %}

    <a href="{% url 'provas_obi:url_buscaprob' %}" class="btn btn-primary"><span>Nova busca</span></a>
{% endblock %}

praticandoOBI/templates/busca/busca_resultado.html
{% extends './busca_form.html' %}
{% load static %}

{% block caminho %}
    {{ block.super }}
    / Resultado
{% endblock %}


{% block container %}
    <p>Resultados para: <strong>{{ query }}</strong></p>
    {% if provas %}
        <p>Encontrou {{provas|length }} prova{{provas|pluralize}}. </p>
        <ul>
            {% for p in provas %}
                <li><a href="{% url 'provas_obi:url_prob' p.codprova %}">{{p.anoprova}} - Fase {{p.faseprova}} - Nível {{p.nivelprova}}</a></li>
            {% endfor %}
        </ul>
    {% else %}
        <p>Nenhum resultado encontrado para a sua pesquisa.</p>
    {% endif %}

    <a href="{% url 'provas_obi:url_busca' %}" class="btn btn-primary"><span>Nova busca</span></a>
{% endblock %}