praticandoOBI/obi/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from provasobi.views import home
from django.conf import settings
from django.conf.urls.static import static
from usuarios.views import activate
from django.conf import settings

urlpatterns = [
                  path('', home, name='home'),
                  path('admin/', admin.site.urls),
                  path('provas/', include('provasobi.urls', namespace='provas_obi')),
                  path('usuario/', include('usuarios.urls', namespace='usuarios_obi')),
                  url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
                      activate, name='activate'),
                  url(r'^nested_admin/', include('nested_admin.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

praticandoOBI/usuarios/urls.py
from django.urls import path
from django.conf.urls import include
from usuarios.views import upload_drive, gabarito, busca, provaperson_baixar, busca, provaperson_excluir, provaperson_baixar_docx, dadosbanco, update_perfil, cadastro_perfil, questoes_add, questoes_busca, home_usuario, provaperson, provaperson_detail, provaperson_edit, provasperson, provaperson_pronta
from django.contrib.auth import views as auth_views

app_name = 'usuarios_obi'
urlpatterns = [
    path('', home_usuario, name='homeusuario'),
    path('cadastro/', cadastro_perfil, name='cadastro_perfil'),

    path('banco/', dadosbanco, name='dadosbanco'),
    path('login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login_perfil'),
    path('login/', include('registration.backends.default.urls')),
    path('logout/', auth_views.LogoutView.as_view(template_name='home.html'), name='logout_perfil'),
    path('minhasprovas/', provasperson, name='provasperson'),
    path('novaprova/', provaperson, name='provaperson'),
    path('minhaprova/editar/<int:pk>/', provaperson_edit, name='provaperson_edit'),
    path('minhaprova/editar/<int:pk>/buscaquestoes/', questoes_busca, name='questoes_busca'),

    path('minhaprova/busca/', busca, name='url_busca'),
    path('minhaprova/editar/<int:pk>/busca/', busca, name='busca'),

    #path('minhaprova/<int:pk>/', provaperson_detail, name='provaperson_detail'),
    # path('minhasprovas/pdf/', Pdf.as_view(), name='provaperson_baixar'),

    path('minhaprova/editar/<int:codproblema>/adquestoes/<int:pk>/', questoes_add, name='questoes_add'),
    path('minhaprova/<int:codprova>/', provaperson_pronta, name='provaperson_pronta'),
    path('minhaprova/excluir/<int:pk>/', provaperson_excluir, name='provaperson_excluir'),

    path('minhaprova/<int:codprova>/gabarito', gabarito, name='url_gabarito'),

    path('minhaprova/<int:codprova>/baixarprova/', provaperson_baixar, name='provaperson_baixar'),
    path('minhaprova/<int:codprova>/baixarprova_docx/', provaperson_baixar_docx, name='provaperson_baixar_docx'),
    path('minhaprova/<int:codprova>/upload_drive/', upload_drive, name='upload_drive'),
]

praticandoOBI/provasobi/models.py
from django.db import models
from usuarios.models import Profile
from django.core.validators import MinValueValidator


class Alternativa(models.Model):
    codalternativa = models.AutoField(db_column='codAlternativa', primary_key=True)  # Field name made lowercase.
    letraalternativa = models.CharField(db_column='letraAlternativa', max_length=10, blank=True,
                                        null=True)  # Field name made lowercase.
    textoalternativa = models.TextField(db_column='textoAlternativa', blank=True,
                                        null=True)  # Field name made lowercase.
    codquestao = models.ForeignKey('Questao', models.CASCADE, db_column='codQuestao', blank=True,
                                   null=True)  # Field name made lowercase.

    class Meta:
        managed = True
        db_table = 'alternativa'
        ordering = ['letraalternativa']

    def __str__(self):
        return self.letraalternativa


class Prova(models.Model):
    codprova = models.AutoField(db_column='codProva', primary_key=True)  # Field name made lowercase.
    anoprova = models.IntegerField(db_column='anoProva', blank=True, null=True)  # Field name made lowercase.
    nivelprova = models.IntegerField(db_column='nivelProva', blank=True, null=True)  # Field name made lowercase.
    faseprova = models.IntegerField(db_column='faseProva', blank=True, null=True)  # Field name made lowercase.
    urlprova = models.URLField(db_column='urlProva', unique=True, null=True, blank=True,
                               default='https://olimpiada.ic.unicamp.br/passadas/')
    urlgabarito = models.URLField(db_column='urlGabarito', unique=True, null=True, blank=True)

    class Meta:
        unique_together = ['anoprova', 'faseprova', 'nivelprova']
        managed = True
        db_table = 'prova'
        ordering = ['anoprova']

    def __str__(self):
        return str(self.anoprova) + '/nivel' + str(self.nivelprova) + '/fase' + str(self.faseprova)


class Problema(models.Model):
    codproblema = models.AutoField(db_column='codProblema', primary_key=True)
    numeroproblema = models.PositiveIntegerField(db_column='numeroProblema',
                                                 validators=[MinValueValidator(1)])
    tituloproblema = models.TextField(db_column='tituloProblema', blank=True, null=True)
    enunciadoproblema = models.TextField(db_column='enunciadoProblema', blank=True, null=True)
    regrasproblema = models.TextField(db_column='regrasProblema', blank=True, null=True)
    imgproblema = models.TextField(db_column='imgProblema', blank=True, null=True, default='')
    codprova = models.ForeignKey('Prova', models.CASCADE, db_column='codProva', blank=True, null=True)
    classificacao = models.ManyToManyField('Classificacao', blank=True)

    def recorte(self, filename):
        return 'problema/' + str(self.codprova.codprova) + '.' + filename.split('.')[-1]

    image = models.ImageField('Recorte', upload_to=recorte, blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'problema'
        unique_together = ['codprova', 'tituloproblema']

    def __str__(self):
        return self.tituloproblema


class Questao(models.Model):
    codquestao = models.AutoField(db_column='codQuestao', primary_key=True)  # Field name made lowercase.
    numeroquestao = models.PositiveIntegerField(db_column='numeroQuestao',
                                                validators=[MinValueValidator(1)])  # Field name made lowercase.
    enunciadoquestao = models.TextField(db_column='enunciadoQuestao', blank=True,
                                        null=True)  # Field name made lowercase.
    alternativas = models.TextField('Alternativas', null=True, blank=True)

    gabaritoquestao = models.CharField(db_column='gabaritoQuestao', max_length=10, blank=True, null=True)
    imgquestao = models.CharField(db_column='imgQuestao', max_length=300, blank=True, null=True, default='')
    codproblema = models.ForeignKey(Problema, models.CASCADE, db_column='codProblema', blank=True, null=True,
                                    related_name="cod_problemas_questao")
    explicativo = models.TextField('Explicação', null=True, blank=True)

    def gabarito(self, filename):
        return 'gabarito/' + str(self.codquestao.codproblema.codprova.codprova) + str(
            self.codquestao.codproblema.numeroproblema) + str(self.codquestao.numeroquestao) + '.' + \
               filename.split('.')[-1]

    explicativo_imagem = models.ImageField('Imagem Explicativa ', null=True, blank=True)

    def recorte(self, filename):
        return 'questao/' + str(self.codproblema.codproblema) + '.' + filename.split('.')[-1]

    image = models.ImageField('Recorte', upload_to=recorte, null=True, blank=True)

    class Meta:
        managed = True
        db_table = 'questao'
        verbose_name_plural = 'Questões'
        verbose_name = 'Questão'
        unique_together = ['codproblema', 'numeroquestao']

    def __str__(self):
        return self.numeroquestao.__str__()

    def get_alternativas(self):
        data = []
        letras = ['A', 'B', 'C', 'D', 'E']
        i = 0
        alternativas = self.alternativas.split('|')
        for alternativa in alternativas:
            data.append({'letraalternativa': letras[i], 'textoalternativa': alternativas[i]})
            i += 1
        return data

# class Gabarito(models.Model):
#     codquestao = models.OneToOneField('Questao', models.DO_NOTHING,
#                                       db_column='codQuestao')  # Field name made lowercase.
#     texto = models.TextField('Explicação', null=True)
#
#     def gabarito(self, filename):
#         return 'gabarito/' + str(self.codquestao.codproblema.codprova.codprova) + str(
#             self.codquestao.codproblema.numeroproblema) + str(self.codquestao.numeroquestao) + '.' + \
#                filename.split('.')[-1]
#
#     imagem = models.ImageField('Imagem Explicativa ', null=True)
#
#     def __str__(self):
#         return self.codquestao.codproblema.tituloproblema + str(self.codquestao.numeroquestao)


class Classificacao(models.Model):
    codclassificacao = models.AutoField(db_column='codClassificacao', primary_key=True)
    tituloclassificacao = models.TextField(db_column='tituloClassificacao', blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'classificacao'
        verbose_name_plural = 'Classificações'
        verbose_name = 'Classificação'

    def __str__(self):
        return self.tituloclassificacao


class ProvaPerson(models.Model):
    autor = models.ForeignKey(Profile, on_delete=models.CASCADE, default='')
    codprovaperson = models.IntegerField(db_column='codProvaPerson', null=True, default='0')
    titulo = models.TextField(db_column='titulo', blank=True, null=True, default='')
    ano = models.CharField(db_column='ano', max_length=20, blank=True, null=True, default='')
    dificuldade = models.IntegerField(db_column='dificuldade', blank=True, null=True, default=0)
    observacoes = models.TextField(db_column='observacoes', blank=True, null=True, default='')
    questoes = models.ManyToManyField(Questao, blank='True')

    def __str__(self):
        return self.autor.user.username

    class Meta:
        verbose_name_plural = 'Provas personalizadas'
        verbose_name = 'Prova personalizada'

praticandoOBI/templates/novasprovas/addquestoes.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}
    Buscar Questões
{% endblock %}

{% block container %}
<link href="{% static 'css/breadcrumb.css' %}" rel="stylesheet">

		<ul class="breadcrumb">
			<li class="completed"><a href="{% url 'usuarios_obi:provaperson' %}">Dados da Prova</a></li>
            <li class="active"><a href="{% url 'usuarios_obi:questoes_busca' pk %}">Buscar Questões</a></li>
            <li><a>Selecionar Questões</a></li>
			<li><a>Prova Pronta!</a></li>
		</ul>

    <h1>Problemas</h1>
    <!--<p>Buscar por título, enunciado, classificacão</p>-->

    <form action="" method="GET">
        <div class="form-group">
            {% if error %}
                <p style="color: red;">Por favor, entre com um valor.</p>
            {% endif %}

            {% if erroinput %}
                <p style="color: red;">Busca inválida, busque por um ano, nível ou fase de prova.</p>
            {% endif %}

            <div class="row">
                <div class="col-10">
                    <input type="text" class="form-control" name="q"/><br/>
                </div>
                <div class="col-2">
                    <button type="submit" class="btn btn-primary btn-block">Buscar</button>
                </div>
            </div>
        </div>
    </form>
    <table id="tableproblemas" class="display">
        <thead>
        <tr>
            <th>Ano / Nível / Fase</th>
            <th>Classificação</th>
            <th>Título</th>
        </tr>
        </thead>
        <tbody>
        {% for problema in problemas %}
            <tr>
                <td>Ano {{ problema.codprova.anoprova }} / Nível {{ problema.codprova.nivelprova }} /
                    Fase {{ problema.codprova.faseprova }}</td>
                <td>{% for class in problema.classificacao.all %}{{ class.tituloclassificacao }} {% endfor %}</td>
                <td><a href="{% url 'usuarios_obi:questoes_add' problema.codproblema pk %}">{{ problema.tituloproblema }}</a></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

{% block extra_scripts %}
    <script>
        $(document).ready(function () {
            $('#tableproblemas').DataTable({"searching": false});
        });
    </script>
{% endblock %}

praticandoOBI/templates/novasprovas/addquestoes_resultado.html
              {% extends './addquestoes.html' %}
{% load static %}

{% block titulo %}
    Buscar Questões
{% endblock %}

{% block container %}
<link href="{% static 'css/breadcrumb.css' %}" rel="stylesheet">
		<ul class="breadcrumb">
			<li class="completed"><a href="{% url 'usuarios_obi:provaperson' %}">Dados da Prova</a></li>
            <li class="active"><a href="{% url 'usuarios_obi:questoes_busca' pk %}">Buscar Questões</a></li>
            <li><a>Selecionar Questões</a></li>
			<li><a>Prova Pronta!</a></li>
		</ul>
    <p>Resultados para: <strong>{{ query }}</strong></p>
    {% if provas %}
        <p>Encontrou {{provas|length }} prova{{provas|pluralize}}. </p>
        <ul>
            {% for p in provas %}
                <li><a href="{% url 'usuarios_obi:questoes_add' pk p.codprova %}">{{p.anoprova}} - Fase {{p.faseprova}} - Nível {{p.nivelprova}}</a></li>
            {% endfor %}
        </ul>
    {% else %}
        <p>Nenhum resultado encontrado para a sua pesquisa.</p>
    {% endif %}
    <a href="{% url 'usuarios_obi:questoes_busca' provaperson.pk %}" class="btn btn-primary"><span>Nova busca</span></a>
{% endblock %}

praticandoOBI/templates/novasprovas/addquestoes_select.html
{% extends './addquestoes_resultado.html' %}
{% load static %}

{% block titulo %}
    Selecionar Questões
{% endblock %}

{% block container %}
    <link href="{% static 'css/breadcrumb.css' %}" rel="stylesheet">

    <br class="list-group">

    <ul class="breadcrumb">
        <li class="completed"><a href="{% url 'usuarios_obi:provaperson' %}">Dados da Prova</a></li>
        <li class="completed"><a href="{% url 'usuarios_obi:questoes_busca' pk %}">Buscar Questões</a></li>
        <li class="active"><a href="">Selecionar Questões</a></li>
        <li><a>Prova Pronta!</a></li>
    </ul>

    <script>
        function toggle(source, f) {
            var checkboxes = document.querySelectorAll('input[name="checks"]');
            for (var i = 0; i < checkboxes.length; i++) {
                    checkboxes[i].checked = source.checked;
            }
        }
    </script>


    <form action="{% url 'usuarios_obi:questoes_busca' pk %}" method="POST" class="post-form">{% csrf_token %}


        <a class="list-group-item">
            <div class="checkbox pull-left">
                <label><input type="checkbox" onclick="toggle(this, {{forloop.counter}})"> Selecionar todos de <b>{{problema.tituloproblema}}</b></label>
            </div>
        <div class="pull-left form-control-inline">
        <h3 class="list-group-item-heading">{{ problema.numeroproblema }} - {{ problema.tituloproblema }}</h3>
                    <h4>Classificação:</h4>
                    <h5>{% for f in problema.classificacao.all %}
                        {{ f.tituloclassificacao }}<br>
                    {% endfor %}</h5>
                    <br/>{{ problema.enunciadoproblema }}</br>

                    {% if problema.regrasproblema %}
                        <br>{{ problema.regrasproblema }}<br>
                    {% endif %}
                    {% if problema.imgproblema %}
                        {% load static %}
                        <img src={% static problema.imgproblema %} width="200" height="200" alt="My image">
                    {% endif %}

            {% for q in questoes %}
                <a class="list-group-item">

                    <div class="checkbox pull-left">
                        <label>
                            <input type="checkbox" name="checks" value="{{ q.codquestao }}"
                                   id="{{ q.codproblema.codproblema }}">
                        </label>
                    </div>

                    <div class="pull-left form-control-inline">
                        <h4 class="list-group-item-heading">{{ q.numeroquestao }}
                            - {{ q.enunciadoquestao }}</h4>
                        <p class="list-group-item-text">
                            <!--Mostra as imagens da questão-->
                            {% if q.imgquestao %}
                                {% load static %}
                                <img src={% static q.imgquestao %} width="200" height="200" alt="Img"></br>
                            {% endif %}

                            <!--Mostra as alternativas da questão-->
                            {% for a in q.get_alternativas %}
                                {{ a.letraalternativa }}) {{ a.textoalternativa }} </br>
                            {% endfor %}
                        </p>
                    </div>
                    <div class="clearfix"></div>
                </a>
            {% endfor %}
            <br class="pull-left form-control-inline"></br>
        </div>
        </a>

        <div class="pull-left form-control-inline">
            <h4 class="list-group-item-heading">
                <button type="submit" class="btn btn-primary">Adicionar e buscar outros</button>
                 <button type="submit" name="finalizar" value="True" class="btn btn-primary">Finalizar</button>
            </h4>
        </div>
    </form>

{% endblock %}

praticandoOBI/templates/novasprovas/gabarito.html
{% extends 'base.html' %}
{% load static %}

{% block titulo %}
    Gabarito
{% endblock %}

{% block container %}

    <p align="center" style="margin-top:5%;">

    {% for p in problemas %}
        {% for q in questoes %}
            {% if p.codproblema == q.codproblema.codproblema %}
            <div class="pull-left form-control-inline">
             <h5 class="list-group-item-heading"><b>Questão {{forloop.counter}} - </b>{{q.gabaritoquestao}}</h5>
            </div>
            {% endif %}
        {% endfor %}
  {% endfor %}
<br>
        <button type="submit" name="finalizar" value="True" class="btn btn-primary">Imprimir Gabarito</button>
    </p>
{% endblock %}

praticandoOBI/templates/novasprovas/provaperson.html
{% extends './../base2.html' %}
{% load static %}

{% block titulo %}
    Nova Prova
{% endblock %}

{% block container %}
<link href="{% static 'css/breadcrumb.css' %}" rel="stylesheet">

    <div class="row">

        <div class="col-md-8 col-sm-10 col-12">
		<ul class="breadcrumb">
			<li class="active"><a href="{% url 'usuarios_obi:provaperson' %}">Dados da Prova</a></li>
            <li><a >Buscar Questões</a></li>
            <li><a >Selecionar Questões</a></li>
			<li><a >Prova Pronta!</a></li>
		</ul>

            <form method="POST" class="post-form">{% csrf_token %}

                <tr>
                <td><label for="id_titulo">Título:</label></td>
                    <div class="form-group">
                     <td><input name="titulo" type="text" required id="id_titulo" class="form-control"></td>
                    </div>
                 </tr>

                <tr>
                <td><label for="id_ano">Ano de criação:</label></td>
                    <div class="form-group">
                        <td><input name="ano" type="text" maxlength="20" id="id_ano" class="form-control"></td>
                    </div>
                 </tr>


                <tr>
                    <td><label for="id_dificuldade">Dificuldade:</label></td><br>
                    <small>Valores de menor para a maior dificuldade</small>
                <div class="row">
                    <div class="form-group form-group-multiple-selectsp col-xs-11 col-sm-8 col-md-4">
                        <div class="input-group input-group-multiple-selectp col-xs-8">
                            <select class="form-control" name="dificuldade">
                                <option value="">Selecione uma</option>
                                <option value="1">1 - Muito fácil</option>
                                <option value="2">2 - Fácil</option>
                                <option value="3">3 - Médio</option>
                                <option value="4">4 - Difícil</option>
                                <option value="5">5 - Muito difícil</option>
                            </select>
                            <span class="input-group-addon input-group-addon-remove">
                                <span class="glyphicon glyphicon-remove"></span>
                            </span>
                        </div>
                    </div></div>
                </tr>


                <tr>
                <td><label for="id_observacoes">Observações:</label></td>
                    <div class="form-group">
                        <td><textarea name="observacoes" cols="40" rows="10" id="id_observacoes" class="form-control"></textarea></td>
                    </div>
                 </tr>

                <a href="{% url 'home' %}" class="btn btn-outline-secondary" role="button" >Cancelar</a>
                <button type="submit" class="btn btn-primary">Adicionar Questões</button>
            </form>
        </div>
    </div>

{% endblock %}

praticandoOBI/templates/novasprovas/provaperson_detail.html
{% extends './../base2.html' %}
{% load static %}

{% block titulo %}
    Minha Prova
{% endblock %}

{% block container %}

    {% for p in provaperson%}
        Título: {{p.titulo}}</br>
        Ano: {{p.ano}}</br>
        Dificuldade: {{p.dificuldade}}</br>
        Observações: {{p.observacoes}}</br></br>
{{p.codprova}}
        <a href="{% url 'usuarios_obi:provaperson_edit' p.pk %}" class="btn btn-primary" role="button" >Editar</a>
        <a href="{% url 'usuarios_obi:provaperson_pronta' p.pk %}" class="btn btn-primary" role="button" >Ver Prova</a>
    {% endfor %}

<a href="{% url 'usuarios_obi:provasperson' %}" class="btn btn-outline-primary" role="button" >Minhas Provas</a>

{% endblock %}

praticandoOBI/templates/novasprovas/provaperson_edit.html
{% extends './../base2.html' %}
{% load static %}

{% block titulo %}
    Minha Prova
{% endblock %}

{% block container %}
<link href="{% static 'css/breadcrumb.css' %}" rel="stylesheet">

    <div class="row">

        <div class="col-md-8 col-sm-10 col-12">
		<ul class="breadcrumb">
			<li class="active"><a href="{% url 'usuarios_obi:provaperson_edit' pk %}">Editar Prova</a></li>
            <li><a>Buscar Questões</a></li>
            <li><a>Selecionar Questões</a></li>
			<li><a>Prova Pronta!</a></li>
		</ul>



            <form method="POST" class="post-form">{% csrf_token %}
                <tr>
                <td><label for="id_titulo">Título:</label></td>
                    <div class="form-group">
                     <td><input name="titulo" type="text" required id="id_titulo" class="form-control" value="{{titulo}}"></td>
                    </div>
                 </tr>

                <tr>
                <td><label for="id_ano">Ano de criação:</label></td>
                    <div class="form-group">
                        <td><input name="ano" type="text" maxlength="20" id="id_ano" class="form-control" value="{{ano}}"></td>
                    </div>
                 </tr>


                <tr>
                    <td><label for="id_dificuldade">Dificuldade:</label></td><br>
                    <small>Valores de menor para a maior dificuldade</small>
                <div class="row">
                    <div class="form-group form-group-multiple-selectsp col-xs-11 col-sm-8 col-md-5">
                        <div class="input-group input-group-multiple-selectp col-xs-8">
                            <select class="form-control" name="dificuldade">
                                {% if dificuldade == None %}
                                    <option selected="selected" value="0">Atual: {{dificuldade}}</option>
                                {% else %}
                                    <option selected="selected" value={{dificuldade}}>Atual: {{dificuldade}}</option>
                                {% endif %}

                                <option value="1">1 - Muito fácil</option>
                                <option value="2">2 - Fácil</option>
                                <option value="3">3 - Médio</option>
                                <option value="4">4 - Difícil</option>
                                <option value="5">5 - Muito difícil</option>
                            </select>
                            <span class="input-group-addon input-group-addon-remove">
                                <span class="glyphicon glyphicon-remove"></span>
                            </span>
                        </div>
                    </div>
                </div>
                </tr>

                <tr>
                <td><label for="id_observacoes">Observações:</label></td>
                    <div class="form-group">
                        <td><input type="text" input name="observacoes" id="id_observacoes" class="form-control" value="{{obs}}"></td>
                    </div>
                 </tr>


        <button type="submit" class="btn btn-primary">Salvar Alterações</button>
        <a href="{% url 'usuarios_obi:questoes_busca' pk %}" class="btn btn-primary" role="button" >Adicionar Questões</a>

        </div>
    </div>
{% endblock %}

praticandoOBI/templates/novasprovas/provaperson_pronta.html
{% extends './addquestoes_select.html' %}
{% load static %}

{% block titulo %}
    Imprimir Prova
{% endblock %}

{% block container %}
<link href="{% static 'css/breadcrumb.css' %}" rel="stylesheet">
		<ul class="breadcrumb">
			<li class="completed"><a href="{% url 'usuarios_obi:provaperson' %}">Dados da Prova</a></li>
			<li class="completed"><a href="{% url 'usuarios_obi:provaperson_edit' codprova %}">Editar Prova</a></li>
            <li class="completed"><a href="{% url 'usuarios_obi:questoes_busca' codprova %}">Buscar Questões</a></li>
            <li class="completed"><a href="{% url 'usuarios_obi:questoes_busca' codprova %}">Adicionar Questões</a></li>
			<li class="active"><a href="{% url 'usuarios_obi:provaperson_baixar' codprova %}">Prova Pronta!</a></li>
		</ul>
<p align="center" style="margin-top:5%;">
    <a href="{% url 'usuarios_obi:provaperson_baixar' codprova %}" class="btn btn-primary" >Download como PDF</a>
    <a href="{% url 'usuarios_obi:provaperson_baixar_docx' codprova %}" class="btn btn-primary" >Download como .docx</a>
    <a href="{% url 'usuarios_obi:upload_drive' codprova %}" class="btn btn-primary" >Salvar no Drive</a>
</p>
<br/>

<br><h3 style="color:#54a9ff;text-align:center;"><b>{{provaperson.titulo}}</b></h3><br><br/>

 {% for p in problemas %}
<h4 class="list-group-item-heading" style="text-align:center;"><b>{{p.tituloproblema}}</b></h4><br/>
<h5>{{p.enunciadoproblema}}</h4>
 <!--Mostra as regras do problema, se ele tiver-->
            {% if p.regrasproblema %}
    <h5><b>REGRAS:</b> {{p.regrasproblema}}<br></h5>
            {% endif %}

            <!--Mostra as imagens do problema, se ele tiver-->
            {% if p.imgproblema %}
                {% load static %}
                <img src={% static p.imgproblema %} width="350" alt="My image">
            {% endif %}
   </br>

   {% for q in questoes %}
     {% if p.codproblema == q.codproblema.codproblema %}
     <div class="pull-left form-control-inline">
         <h5 class="list-group-item-heading"><b>Questão {{forloop.counter}} - </b>{{q.enunciadoquestao}}</h5>
         <p class="list-group-item-text">
               <!--Mostra as imagens da questão-->
              {% if q.imgquestao %}
                  {% load static %}
                  <img src={% static q.imgquestao %} width="200" height="200" alt="Img"></br>
              {% endif %}

                <!--Mostra as alternativas da questão-->
                {% for a in q.get_alternativas %}
                    {{ a.letraalternativa }}) {{ a.textoalternativa }} </br>
                {% endfor %}
          </p>
      </div>

     {% endif %}
   {% endfor %}
    <hr>
  {% endfor %}

    <p align="center" style="margin-top:5%;">
    <a href="{% url 'usuarios_obi:url_gabarito' codprova %}" class="btn btn-primary" >Gabarito</a>
    </p>

{% endblock %}