praticandoOBI/obi/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from provasobi.views import home
from django.conf import settings
from django.conf.urls.static import static
from usuarios.views import activate
from django.conf import settings

urlpatterns = [
                  path('', home, name='home'),
                  path('admin/', admin.site.urls),
                  path('provas/', include('provasobi.urls', namespace='provas_obi')),
                  path('usuario/', include('usuarios.urls', namespace='usuarios_obi')),
                  url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
                      activate, name='activate'),
                  url(r'^nested_admin/', include('nested_admin.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

praticandoOBI/usuarios/urls.py
from django.urls import path
from django.conf.urls import include
from usuarios.views import upload_drive, gabarito, busca, provaperson_baixar, busca, provaperson_excluir, provaperson_baixar_docx, dadosbanco, update_perfil, cadastro_perfil, questoes_add, questoes_busca, home_usuario, provaperson, provaperson_detail, provaperson_edit, provasperson, provaperson_pronta
from django.contrib.auth import views as auth_views

app_name = 'usuarios_obi'
urlpatterns = [
    path('', home_usuario, name='homeusuario'),
    path('cadastro/', cadastro_perfil, name='cadastro_perfil'),

    path('banco/', dadosbanco, name='dadosbanco'),
    path('login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login_perfil'),
    path('login/', include('registration.backends.default.urls')),
    path('logout/', auth_views.LogoutView.as_view(template_name='home.html'), name='logout_perfil'),
    path('minhasprovas/', provasperson, name='provasperson'),
    path('novaprova/', provaperson, name='provaperson'),
    path('minhaprova/editar/<int:pk>/', provaperson_edit, name='provaperson_edit'),
    path('minhaprova/editar/<int:pk>/buscaquestoes/', questoes_busca, name='questoes_busca'),

    path('minhaprova/busca/', busca, name='url_busca'),
    path('minhaprova/editar/<int:pk>/busca/', busca, name='busca'),

    #path('minhaprova/<int:pk>/', provaperson_detail, name='provaperson_detail'),
    # path('minhasprovas/pdf/', Pdf.as_view(), name='provaperson_baixar'),

    path('minhaprova/editar/<int:codproblema>/adquestoes/<int:pk>/', questoes_add, name='questoes_add'),
    path('minhaprova/<int:codprova>/', provaperson_pronta, name='provaperson_pronta'),
    path('minhaprova/excluir/<int:pk>/', provaperson_excluir, name='provaperson_excluir'),

    path('minhaprova/<int:codprova>/gabarito', gabarito, name='url_gabarito'),

    path('minhaprova/<int:codprova>/baixarprova/', provaperson_baixar, name='provaperson_baixar'),
    path('minhaprova/<int:codprova>/baixarprova_docx/', provaperson_baixar_docx, name='provaperson_baixar_docx'),
    path('minhaprova/<int:codprova>/upload_drive/', upload_drive, name='upload_drive'),
]

praticandoOBI/usuarios/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    localizacao = models.CharField(max_length=100, blank=True, default='')
    instituicao = models.CharField(max_length=100, blank=True, default='')
    data_nascimento = models.DateField(null=True, blank=True)

    def __str__(self):
        return  self.user.username



@receiver(post_save, sender=User)
def update_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()

praticandoOBI/usuarios/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from provasobi.models import ProvaPerson

class ProvaForm(forms.ModelForm):
    class Meta:
        model = ProvaPerson
        fields = ('titulo', 'ano', 'dificuldade', 'observacoes',)


class QuestoesForm(forms.ModelForm):
    class Meta:
        model = ProvaPerson
        fields = ('titulo', 'ano', 'dificuldade', 'observacoes',)


# class UserForm(forms.ModelForm):
#     class Meta:
#         model = User
#         fields = ('first_name', 'last_name', 'username', 'email',)

class ProfileForm(UserCreationForm):
    data_nascimento = forms.DateField(required=False, help_text='Formato: YYYY-MM-DD')
    localizacao = forms.CharField(required=False, help_text='Estado')
    instituicao = forms.CharField(required=False, help_text='Instituição de Ensino')

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'data_nascimento', 'localizacao', 'instituicao', 'password1', 'password2',)

    # @transaction.atomic
    # def save(self, data_nascimento, localizacao, instituicao):
    #     user = super().save(commit=False)
    #     user.save()
    #     Profile.objects.create(user=user)
    #     user.profile.data_nascimento = data_nascimento
    #     user.profile.localizacao = localizacao
    #     user.profile.instituicao = instituicao
    #     user.profile.save()
    #     return user

praticandoOBI/usuarios/views.py
# -*- coding: utf-8 -*-
import codecs
from django.shortcuts import render, redirect, get_object_or_404
import os
from .forms import ProfileForm, ProvaForm, QuestoesForm
from provasobi.models import ProvaPerson, Prova, Questao, Classificacao, Problema, Alternativa
from django.contrib import messages
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import inch
from django.core.files.storage import FileSystemStorage
from django.http import HttpResponse

from docx import Document
from docx.shared import Inches, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH

from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from .tokens import account_activation_token
from django.contrib.auth.models import User
from django.core.mail import EmailMessage

# API DRIVE:
from googleapiclient.discovery import build
from httplib2 import Http
from oauth2client import file, client, tools
from apiclient.http import MediaFileUpload

from watson import search as watson

# If modifying these scopes, delete the file token.json.
SCOPES = 'https://www.googleapis.com/auth/drive'


# @login_required
def home_usuario(request):
    return render(request, 'usuarios/homeusuario.html', {})


def update_perfil(request):
    if request.method == 'POST':
        user_form = UserForm(request.POST, instance=request.user)
        profile_form = ProfileForm(request.POST, instance=request.user.profile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'Perfil atualizado.')
            return redirect('home')
        else:
            messages.error(request, 'Corrija os erros.')
    else:
        user_form = UserForm(instance=request.user)
        profile_form = ProfileForm(instance=request.user.profile)
    return render(request, 'usuarios/perfil.html', {'user_form': user_form, 'profile_form': profile_form})


def cadastro_perfil(request):
    error = False
    if request.method == 'POST':
        form = ProfileForm(request.POST)
        if form.is_valid():
            error = False
            user = form.save()
            user.refresh_from_db()  # load the profile instance created by the signal
            user.profile.data_nascimento = form.cleaned_data.get('data_nascimento')

            user.profile.instituicao = form.cleaned_data.get('instituicao')
            user.profile.localizacao = form.cleaned_data.get('localizacao')

            to_email = form.cleaned_data.get('email')
            user.is_active = False
            user.save()

            current_site = get_current_site(request)
            print(current_site)  # AQUI: SETAR SITE PRO HEROKU
            mail_subject = 'Ative sua conta no Praticando OBI'
            message = render_to_string('registration/acc_active_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)).decode(),
                'token': account_activation_token.make_token(user),
            })

            email = EmailMessage(mail_subject, message, to=[to_email])
            email.send()
            return render(request, 'registration/confirmacao.html', {})
        else:
            error = True
    else:
        form = ProfileForm()
    return render(request, 'usuarios/signup.html', {'form': form, 'error': error})


def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)
        # return redirect('home')
        messages.success(request, 'Obrigado por confirmar sua conta!')
        return render(request, 'registration/login.html', {})
    else:
        return redirect('home')


def provaperson(request):
    if request.method == "POST":
        form = ProvaForm(request.POST)
        if form.is_valid():
            provaperson = form.save(commit=False)
            provaperson.autor = request.user.profile
            provaperson.save()
            return redirect('usuarios_obi:questoes_busca', provaperson.pk)
    else:
        form = ProvaForm()
    return render(request, 'novasprovas/provaperson.html', {'form': form})


def provaperson_excluir(request, pk):
    provaperson = get_object_or_404(ProvaPerson, pk=pk)
    provaperson.delete()
    return redirect('usuarios_obi:provasperson')


def provaperson_edit(request, pk):
    provaperson = get_object_or_404(ProvaPerson, pk=pk)
    if request.method == "POST":
        form = ProvaForm(request.POST, instance=provaperson)
        if form.is_valid():
            provaperson = form.save(commit=False)
            provaperson.autor = request.user.profile
            provaperson.save()
            messages.success(request, "Alterações salvas!")
            return redirect('usuarios_obi:provaperson_edit', provaperson.pk)
    else:
        form = ProvaForm(instance=provaperson)

    return render(request, 'novasprovas/provaperson_edit.html',
                  {'form': form, 'pk': pk, 'titulo': provaperson.titulo, 'ano': provaperson.ano,
                   'dificuldade': provaperson.dificuldade, 'obs': provaperson.observacoes})


# mostra as provas criadas
def provasperson(request):
    provas = ProvaPerson.objects.filter(autor=request.user.profile)
    return render(request, 'minhasprovas.html', {'provas': provas})


def provaperson_detail(request, pk):
    provaperson = ProvaPerson.objects.all().filter(pk=pk)
    return render(request, 'novasprovas/provaperson_detail.html', {'provaperson': provaperson})


def gabarito(request, codprova):
    provaperson = get_object_or_404(ProvaPerson, pk=codprova, autor=request.user.profile)
    questoes = Questao.objects.all().filter(codquestao__in=provaperson.questoes.all()).order_by('numeroquestao')

    id_problemas = Questao.objects.all().filter(codquestao__in=provaperson.questoes.all()).values('codproblema')
    problemas = Problema.objects.all().filter(codproblema__in=id_problemas).distinct()

    return render(request, 'novasprovas/gabarito.html',
                  {'provaperson': provaperson, 'problemas': problemas, 'questoes': questoes, 'codprova': codprova})


def busca(request):
    error = False
    provas = Prova.objects.all()
    q = request.GET.get('q', '')
    problemas = Problema.objects.all()
    if q:
        problemas = watson.filter(problemas, q)

    return render(request, 'novasprovas/addquestoes.html', {'provas': provas,
                                                            'error': error,
                                                            'problemas': problemas})

def questoes_busca(request, pk):
    provaperson = get_object_or_404(ProvaPerson, pk=pk, autor=request.user.profile)
    q = request.GET.get('q', '')
    problemas = Problema.objects.all()
    if q:
        problemas = watson.filter(problemas, q)

    if request.method == 'POST':
        id_questoes = request.POST.getlist('checks')

        for q in id_questoes:
            provaperson.questoes.add(q)

        if request.POST.get('finalizar', False):
            return redirect('usuarios_obi:provaperson_pronta', codprova=pk)

    return render(request, 'novasprovas/addquestoes.html',
                  {'provaperson': provaperson, 'pk': pk, 'problemas': problemas})


def questoes_add(request, codproblema, pk):
    problema = Problema.objects.get(codproblema=codproblema)
    questoes = Questao.objects.filter(codproblema=codproblema).order_by('numeroquestao')  # .filter(codproblema__in=id_questoes)
    return render(request, 'novasprovas/addquestoes_select.html',
                  {'problema': problema, 'questoes': questoes, 'pk': pk})


def provaperson_pronta(request, codprova):
    provaperson = get_object_or_404(ProvaPerson, pk=codprova, autor=request.user.profile)
    questoes = Questao.objects.all().filter(codquestao__in=provaperson.questoes.all()).order_by('numeroquestao')

    id_problemas = Questao.objects.all().filter(codquestao__in=provaperson.questoes.all()).values('codproblema')
    problemas = Problema.objects.all().filter(codproblema__in=id_problemas).distinct()

    return render(request, 'novasprovas/provaperson_pronta.html',
                  {'provaperson': provaperson, 'problemas': problemas, 'questoes': questoes, 'codprova': codprova})


acentoserro = ["á", "à", "ã", "Ã", "é", "ê", "õ", "ô", "ó", "ç", "ú", "ı́"]
acentos = ["á", "à", "ã", "Ã", "é", "ê", "õ", "ô", "ó", "ç", "ú", "í"]

def provaperson_baixar(request, codprova):

    provaperson = get_object_or_404(ProvaPerson, pk=codprova, autor=request.user.profile)
    questoes = Questao.objects.all().filter(codquestao__in=provaperson.questoes.all()).order_by('numeroquestao')

    id_problemas = Questao.objects.all().filter(codquestao__in=provaperson.questoes.all()).values('codproblema')
    problemas = Problema.objects.all().filter(codproblema__in=id_problemas).distinct()

    count = 1
    doc = SimpleDocTemplate("/tmp/prova-" + str(codprova) + ".pdf", rightMargin=50, leftMargin=50, topMargin=40, bottomMargin=50)
    styles = getSampleStyleSheet()
    Story = [Spacer(1, 0.2 * inch)]
    style = styles["Normal"]
    par = Paragraph('<para align=center fontSize=20 > <b>' + provaperson.titulo + '</b></para>', style)
    Story.append(par)
    Story.append(Spacer(1, 0.4 * inch))

    for p in problemas:

praticandoOBI/templates/usuarios/homeusuario.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}

{% block caminho %}
    Usuário
{% endblock %}

{% block container %}
    <a href = "{% url 'usuarios_obi:cadastro_perfil' %}">Cadastrar</a><br/>
    <a href="{% url 'usuarios_obi:login_perfil' %}" class="top-menu">Fazer Login</a><br/>
{% endblock %}

praticandoOBI/templates/usuarios/perfil.html
<!DOCTYPE html>
{% extends './../base.html' %}
{% load static %}

{% block caminho %}
    Perfil
{% endblock %}


{% block container %}

    <h2>Olá: {{ user.nome }}</h2>
<!--<ul>-->
    <!--<li>Nome: {{user.username}}</li>-->
    <!--<li>Local: {{user.localizacao}} </li>-->
    <!--<li>Data de Nascimento: {{user.data_nascimento}} </li>-->
<!--</ul>-->
    <form method="POST" class="post-form" >{% csrf_token %}
      {{ user_form.as_p }}
      {{ profile_form.as_p }}
      <button type="submit">Salvar</button>
    </form>
{% endblock %}

praticandoOBI/templates/usuarios/signup.html
{% extends './../base2.html' %}
{% load static %}

{% block titulo %}
    Cadastro
{% endblock %}

{% block container %}
    <script>
        jQuery(document).ready(function () {
            $("#showpassword").on('click', function () {
                var pass = $("#id_password1");
                var fieldtype = pass.attr('type');
                if (fieldtype == 'password') {
                    pass.attr('type', 'text');
                    $(this).text("Esconder Senha");
                } else {
                    pass.attr('type', 'password');
                    $(this).text("Mostrar Senha");
                }

                var pass = $("#id_password2");
                var fieldtype = pass.attr('type');
                if (fieldtype == 'password') {
                    pass.attr('type', 'text');
                    $(this).text("Esconder Senha");
                } else {
                    pass.attr('type', 'password');
                    $(this).text("Mostrar Senha");
                }
            });
        });
    </script>

    {% if error %}
        <div class="error-message">
            <div class="alert alert-danger">
                <h5>Dados inválidos... </h5>
            </div>
        </div>
    {% endif %}

    {% for error in form.non_field_errors %}
        <div class="error-message">
            <div class="alert alert-danger">
                {{ error }}
            </div>
        </div>
    {% endfor %}

    {% for field in form %}
        {% for error in field.errors %}
            <div class="error-message">
                <div class="alert alert-danger">
                    {{ error }}
                </div>
            </div>
        {% endfor %}

    {% endfor %}

    <form method="post">{% csrf_token %}
        <table class="table">

            <tr>
                <td><label for="id_first_name">Nome:</label></td>
                <div class="form-group">
                    <td><input id="id_first_name" name="first_name" type="text" maxlength="30" class="form-control">
                    </td>
                </div>
            </tr>

            <tr>
                <td><label for="id_last_name">Sobrenome:</label></td>
                <div class="form-group">
                    <td><input id="id_last_name" name="last_name" type="text" maxlength="150" class="form-control"></td>
                </div>
            </tr>

            <tr>
                <td><label for="id_username">Usuário:</label></td>
                <div class="form-group">
                    <td><input name="username" type="text" maxlength="100" autofocus required id="id_username"
                               class="form-control">
                        <small style="color:red;">
                            <li><span class="helptext">Obrigatório.</span></li>
                        </small>
                    </td>
                </div>
            </tr>

            <tr>
                <td><label for="id_email">Email:</label></td>
                <div class="form-group">
                    <td><input name="email" type="email" maxlength="200" required id="id_email" class="form-control">
                        <small style="color:red;">
                            <li><span class="helptext">Obrigatório.</span></li>
                        </small>
                    </td>
                </div>
            </tr>

            <tr>
                <td><label for="id_data_nascimento">Data de Nascimento:</label></td>
                <div class="form-group">
                    <td>
                        <input type="date" name="data_nascimento" id="id_data_nascimento">
                    </td>
                </div>
            </tr>

            <tr>
                <td><label for="id_localizacao">Estado:</label></td>
                <div class="form-group">
                    <td>
                        <select name="localizacao" id="id_localizacao">
                            <option value="None">---</option>
                            <option value="AC">Acre</option>
                            <option value="AL">Alagoas</option>
                            <option value="AP">Amapá</option>
                            <option value="AM">Amazonas</option>
                            <option value="BA">Bahia</option>
                            <option value="CE">Ceará</option>
                            <option value="DF">Distrito Federal</option>
                            <option value="ES">Espírito Santo</option>
                            <option value="GO">Goiás</option>
                            <option value="MA">Maranhão</option>
                            <option value="MT">Mato Grosso</option>
                            <option value="MS">Mato Grosso do Sul</option>
                            <option value="MG">Minas Gerais</option>
                            <option value="PA">Pará</option>
                            <option value="PB">Paraíba</option>
                            <option value="PR">Paraná</option>
                            <option value="PE">Pernambuco</option>
                            <option value="PI">Piauí</option>
                            <option value="RJ">Rio de Janeiro</option>
                            <option value="RN">Rio Grande do Norte</option>
                            <option value="RS">Rio Grande do Sul</option>
                            <option value="RO">Rondônia</option>
                            <option value="RR">Roraima</option>
                            <option value="SC">Santa Catarina</option>
                            <option value="SP">São Paulo</option>
                            <option value="SE">Sergipe</option>
                            <option value="TO">Tocantins</option>
                        </select>
                    </td>
                </div>
            </tr>

            <tr>
                <td><label for="id_instituicao">Instituição de Ensino:</label></td>
                <div class="form-group">
                    <td><input name="instituicao" type="text" id="id_instituicao" class="form-control">
                    </td>
                </div>
            </tr>

            <tr>
                <td><label for="id_password1">Senha:</label></td>
                <div class="form-group">
                    <td><input name="password1" type="password" required id="id_password1" class="form-control">
                        <small>
                            <li>Mínimo 8 caracteres, não toda numérica e distinta do seu nome e usuário.</li>
                        </small>
                    </td>
                </div>
            </tr>

            <tr>
                <td><label for="id_password2">Confirmação da Senha:</label></td>
                <div class="form-group">
                    <td><input name="password2" type="password" required id="id_password2" class="form-control">
                    </td>
                </div>
            </tr>

        </table>

        <button class="btn btn-info" type="button" name="showpassword" id="showpassword" value="Show Password">Mostrar
            senha
        </button>
        <a href="{% url 'home' %}" class="btn btn-outline-secondary" role="button">Cancelar</a>
        <button type="submit" class="btn btn-primary">Entrar</button>

    </form>

{% endblock %}